version: "3.5"


services:

  conv-ui:
    image: "redit/conv-ui:latest"
    ports:
      - "5443:443"
    networks:
      - conv-network

  conv-app:
    image: "redit/conv-app:latest"
    ports:
      - "5444:8080"
    networks:
      - conv-network
    depends_on:
      - conv-db

  conv-db:
    image: "mariadb:10.2.17-bionic"
    networks:
      - conv-network
    ports:
      - "3319:3306"
    environment:
      - 'MYSQL_ROOT_PASSWORD=redit9'
    volumes:
      - "db-store:/var/lib/mysql"

networks:
  conv-network:

volumes:
  db-store: